### ISSUE TITLE
Gogoanime Down

### ISSUE THREAD

**Issue by Axe090** [jakepurple13/OtakuWorld#220]
Gogoanime source is not working.

**Comment by jakepurple13** [comment]
I know. I'm kinda being selfish keeping it in since it was nice to see all the anime I favorited with it. In the next update I'll remove it and/or replace it with another gogoanime.

**Comment by jakepurple13** [comment]
Replacing the source with gogoanime.vc.

**Comment by jakepurple13** [comment]
Change made in #219 b4402ed6d5aa4c15ada404f4c33e8323235b8cc9
