### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by BIGEAZY289** [jakepurple13/OtakuWorld#268]
Animeworld crashing on redmi note 4

**Comment by BIGEAZY289** [comment]
What source?

**Comment by jakepurple13** [comment]
Can you clear cache and storage?

**Comment by jakepurple13** [comment]
I just put out a new update https://github.com/jakepurple13/OtakuWorld/releases/tag/v29.0.0 . Can you download it and try it out?

**Comment by BIGEAZY289** [comment]
Still the same

**Comment by jakepurple13** [comment]
Can you try to see if manga world works?

**Comment by jakepurple13** [comment]
I'm making a special build that has some extra handling. https://github.com/jakepurple13/OtakuWorld/releases/tag/v29.0.1 It should be ready in about an hour of this comment. Please try it out when you have the time.

**Comment by jakepurple13** [comment]
Any updates? If not I'll close this issue tomorrow.
