### ISSUE TITLE
New Source 

### ISSUE THREAD

**Issue by OshekharO** [jakepurple13/OtakuWorld#502]
Please add this source: www.mangaread.org

**Comment by jakepurple13** [comment]
Just pushed a commit to include that source.
I think I'll do an update sometime next week. I will be testing and making sure the new source works over the weekend though 😛 

There will be a lot of changes (not all completely visual) that will be in the next update.

**Comment by OshekharO** [comment]
> Just pushed a commit to include that source. I think I'll do an update sometime next week. I will be testing and making sure the new source works over the weekend though 😛
> 
> There will be a lot of changes (not all completely visual) that will be in the next update.

I have one suggestion instead of adding mangaread why don't you just make madara theme parser in which all the manga sources which uses madara theme can be added.
