### ISSUE TITLE
TV Ver. Crashing!? 

### ISSUE THREAD

**Issue by MarshMeadow** [jakepurple13/OtakuWorld#699]
I can't open it, well... I can it just waits a sec, I can't do anything, I did once do something, and after a sec it crashes...

**Comment by jakepurple13** [comment]
I'm seeing the crash in crashlytics. I'll look into it.

**Comment by jakepurple13** [comment]
I should have fixed it with https://github.com/jakepurple13/OtakuWorld/releases/tag/v30.0.2
